#!/usr/bin/env bash
#
# Verify the database layer against a real Postgres.
#
#   1. applies every migration in order, which is the upgrade path production
#      will actually take
#   2. runs the SQL test suite against the result
#   3. applies the consolidated schema.sql to a second, empty database and
#      checks it produces the same thing — that snapshot is hand-maintained, so
#      this is what stops it drifting from the migrations
#
# Needs psql on PATH and a Postgres to talk to. Connection comes from the usual
# PG* environment variables (PGHOST, PGPORT, PGUSER, PGPASSWORD); anything you
# don't set falls back to psql's own defaults.
#
# Usage:  supabase/tests/verify.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"

MIG_DB="${MIG_DB:-lead_db_migrations}"
SNAP_DB="${SNAP_DB:-lead_db_snapshot}"

# psql against the maintenance database, for create/drop database.
admin_psql() { psql -v ON_ERROR_STOP=1 -q -d postgres "$@"; }
# psql against one of our scratch databases.
run_psql() { psql -v ON_ERROR_STOP=1 -q "$@"; }

say() { printf '\n== %s\n' "$1"; }

reset_db() {
  local db="$1"
  admin_psql -c "drop database if exists \"$db\"" >/dev/null
  admin_psql -c "create database \"$db\"" >/dev/null
  # auth.uid, storage.buckets, the realtime publication and a cron stub: objects
  # the Supabase platform provides that a bare Postgres does not.
  run_psql -d "$db" -f "$here/_local_supabase_stubs.sql" >/dev/null
}

# Dump the shape of a database so two of them can be compared.
dump_shape() {
  local db="$1" out="$2"
  {
    psql -t -A -d "$db" -c \
      "select table_name||'.'||column_name||' '||data_type
         from information_schema.columns
        where table_schema='public' order by 1"
    psql -t -A -d "$db" -c \
      "select p.proname||'('||pg_get_function_identity_arguments(p.oid)||')'
         from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname='public' order by 1"
    psql -t -A -d "$db" -c \
      "select conrelid::regclass||' '||pg_get_constraintdef(oid)
         from pg_constraint
        where connamespace='public'::regnamespace and contype='c' order by 1"
  } > "$out"
}

say "Applying migrations to $MIG_DB"
reset_db "$MIG_DB"
for f in "$repo"/supabase/migrations/*.sql; do
  # pg_cron is a Supabase-managed extension and cannot be installed here; the
  # two calls the migrations make are stubbed in _local_supabase_stubs.sql.
  sed '/create extension if not exists pg_cron/d' "$f" | run_psql -d "$MIG_DB"
  printf '   applied %s\n' "$(basename "$f")"
done

say "Running the SQL test suite"
for t in "$here"/*_test.sql; do
  printf '   %s\n' "$(basename "$t")"
  run_psql -d "$MIG_DB" -f "$t"
done

say "Applying schema.sql to $SNAP_DB"
reset_db "$SNAP_DB"
sed '/create extension if not exists pg_cron/d' "$repo/supabase/schema.sql" \
  | run_psql -d "$SNAP_DB"

# schema.sql claims to be idempotent, so prove it rather than trusting it.
sed '/create extension if not exists pg_cron/d' "$repo/supabase/schema.sql" \
  | run_psql -d "$SNAP_DB"
printf '   applied twice, cleanly\n'

say "Comparing schema.sql against the migration path"
dump_shape "$MIG_DB" /tmp/shape.migrations
dump_shape "$SNAP_DB" /tmp/shape.snapshot
if diff -u /tmp/shape.migrations /tmp/shape.snapshot; then
  printf '   identical: columns, functions and check constraints all match\n'
else
  cat >&2 <<'MSG'

schema.sql has drifted from the migrations.

schema.sql is a consolidated snapshot, regenerated by hand. When you add a
migration you have to fold the same change into it. The diff above shows what
the snapshot is missing (-) or has that the migrations do not (+).
MSG
  exit 1
fi

say "Database verification passed"
