/**
 * Reading the gross revenue figure out of a Stayful property-analysis PDF.
 *
 * The report is generated by the analyser and states the property's projected
 * short-term-let revenue in two places — a headline block and a "Revenue
 * Breakdown" table — which agree with one another. Both render as
 * `Gross Revenue £<annual> £<monthly>` once the page text is flattened.
 *
 * THE DOCUMENT NEVER REACHES A CUSTOMER. Nothing here stores or returns the
 * PDF, its URL, or any other figure it contains. The report is downloaded,
 * read for one number, and discarded.
 *
 * A MIS-PARSE MUST FAIL SILENT. A wrong income figure is worse than no figure,
 * because an operator prices a call on it — so this returns null on anything it
 * cannot corroborate, and never throws. Two independent cross-checks below.
 */

/** Collapse a PDF's text layer to a single line of single-spaced text. */
function flatten(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function toNumber(raw: string): number {
  return Number(raw.replace(/,/g, ""));
}

/**
 * `Gross Revenue £36,112 £3,009`. Case-insensitive because the headline block
 * shouts it and the breakdown table title-cases it; the first match wins and
 * both carry the same pair.
 */
const GROSS_RE = /Gross\s+Revenue\s*£\s*([\d,]+)\s*£\s*([\d,]+)/i;

/**
 * The report's own fee line, used only to corroborate. Absent from some
 * layouts, which is fine — it is a guard, not a requirement.
 */
const FEE_RE = /Management\s+Fees\s*\(15%\)\s*£\s*([\d,]+)/i;

/** The stated monthly must be the stated annual over twelve, within rounding. */
const MONTHLY_TOLERANCE = 0.02;
/** The report's own fee line must agree with gross / 6.667. */
const FEE_TOLERANCE = 0.01;

const MANAGEMENT_FEE_DIVISOR = 6.667;

/**
 * The projected gross annual revenue, or null if the document does not state
 * one we can trust.
 *
 * Null covers three different documents and the caller cannot tell them apart,
 * which is deliberate — all three mean "no figure": a legacy third-party
 * valuation with no such section, a current report whose format has moved, and
 * a corrupt download. The sweep records the status; only the transient case is
 * retried, and that is decided by whether this threw at the fetch, not here.
 */
export async function parseGrossAnnualIncome(
  bytes: Uint8Array
): Promise<number | null> {
  let flat: string;
  try {
    // Imported lazily so the parser is only pulled into a lambda that actually
    // reads a PDF — the ingest path reaches this on new leads only.
    const { extractText, getDocumentProxy } = await import("unpdf");
    const doc = await getDocumentProxy(bytes);
    const { text } = await extractText(doc, { mergePages: true });
    flat = flatten(Array.isArray(text) ? text.join(" ") : text);
  } catch (err) {
    // Message only, not the object: a legacy third-party valuation on an old
    // item takes this path routinely, and a stack trace per lead would bury the
    // failures that actually mean something.
    console.error(
      "parseGrossAnnualIncome: could not read PDF —",
      err instanceof Error ? err.message : String(err)
    );
    return null;
  }

  const match = flat.match(GROSS_RE);
  if (!match) return null;

  const annual = toNumber(match[1]);
  const monthly = toNumber(match[2]);
  if (!Number.isFinite(annual) || annual <= 0) return null;

  // Cross-check 1 — the two figures on the same line must be the same figure.
  // This is what stops a match that has straddled two unrelated table cells:
  // any such pair fails the twelve-times relationship immediately.
  if (!Number.isFinite(monthly) || monthly <= 0) return null;
  const expectedMonthly = annual / 12;
  if (Math.abs(monthly - expectedMonthly) / expectedMonthly > MONTHLY_TOLERANCE) {
    console.error(
      `parseGrossAnnualIncome: monthly ${monthly} does not match annual ${annual} / 12`
    );
    return null;
  }

  // Cross-check 2 — where the report states its own management fee, it must be
  // the fee we are about to show. If the analyser ever changes what it means by
  // gross, this is the line that catches it rather than the customer.
  const fee = flat.match(FEE_RE);
  if (fee) {
    const stated = toNumber(fee[1]);
    const expected = annual / MANAGEMENT_FEE_DIVISOR;
    if (
      !Number.isFinite(stated) ||
      Math.abs(stated - expected) / expected > FEE_TOLERANCE
    ) {
      console.error(
        `parseGrossAnnualIncome: stated fee ${stated} does not match gross ${annual} / ${MANAGEMENT_FEE_DIVISOR}`
      );
      return null;
    }
  }

  return annual;
}

// ---------------------------------------------------------------------------
// Fetching a report and turning the outcome into columns.
//
// Shared by ingest (new leads, inline) and /api/cron/parse-income-reports (the
// backlog and retries), so the two can never disagree about what a given
// outcome means. No Supabase import here on purpose: this returns a patch, the
// callers own their own writes.
// ---------------------------------------------------------------------------

export type IncomeReportStatus =
  | "pending"
  | "parsed"
  | "no_report"
  | "unparsed"
  | "failed";

export interface IncomeReportOutcome {
  status: IncomeReportStatus;
  grossAnnualIncome: number | null;
  assetId: string | null;
  error: string | null;
}

/** Matches the lead-files ceiling; an analysis is ~25 KB, so this is a bound on nonsense. */
const MAX_REPORT_BYTES = 25 * 1024 * 1024;

/** Matches MONDAY_TIMEOUT_MS. The money path must never wait longer than this. */
const DOWNLOAD_TIMEOUT_MS = 8000;

/**
 * Download a report and read its gross figure.
 *
 * NEVER THROWS. A lead with no income figure is a lead that looks the way every
 * lead looked last week; a lead that failed to ingest is a landlord nobody
 * rings. Every failure becomes a status.
 *
 * `failed` is the only outcome the sweep retries, and it is reserved for things
 * that might work next time — an unreachable host, a truncated download. A PDF
 * we read and could not trust is `unparsed`, which is a permanent fact about
 * that document and is not retried.
 */
export async function resolveIncomeReport(
  asset: { id: string; public_url: string } | null,
  timeoutMs: number = DOWNLOAD_TIMEOUT_MS
): Promise<IncomeReportOutcome> {
  if (!asset?.public_url) {
    return { status: "no_report", grossAnnualIncome: null, assetId: null, error: null };
  }

  let bytes: Uint8Array;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(asset.public_url, {
      cache: "no-store",
      signal: controller.signal,
    });
    if (!res.ok) {
      return {
        status: "failed",
        grossAnnualIncome: null,
        assetId: asset.id,
        error: `Report download HTTP ${res.status}`,
      };
    }
    const buf = await res.arrayBuffer();
    if (buf.byteLength > MAX_REPORT_BYTES) {
      return {
        status: "unparsed",
        grossAnnualIncome: null,
        assetId: asset.id,
        error: `Report is ${buf.byteLength} bytes, over the ${MAX_REPORT_BYTES} limit`,
      };
    }
    bytes = new Uint8Array(buf);
  } catch (err) {
    return {
      status: "failed",
      grossAnnualIncome: null,
      assetId: asset.id,
      error: err instanceof Error ? err.message : "Report download failed",
    };
  } finally {
    clearTimeout(timer);
  }

  const gross = await parseGrossAnnualIncome(bytes);
  if (gross == null) {
    return {
      status: "unparsed",
      grossAnnualIncome: null,
      assetId: asset.id,
      error: "No trustworthy gross revenue figure in the report",
    };
  }

  return { status: "parsed", grossAnnualIncome: gross, assetId: asset.id, error: null };
}

/**
 * The `leads` patch for an outcome.
 *
 * gross_annual_income is written on EVERY outcome, so a report that is replaced
 * with an unreadable one clears the old figure rather than leaving a stale
 * number attributed to a document that no longer says it.
 */
export function incomeReportPatch(
  outcome: IncomeReportOutcome
): Record<string, unknown> {
  return {
    gross_annual_income: outcome.grossAnnualIncome,
    income_report_status: outcome.status,
    income_report_asset_id: outcome.assetId,
    income_report_parsed_at: new Date().toISOString(),
    income_report_error: outcome.error,
  };
}
