// GENERATED BY scripts/generate-ad-spec-prose.mjs — DO NOT EDIT.
// Source: docs/landlord-ad-template-pack-v1.md (spec v1, 2026-09-20).
// Re-run: npm run gen:ads   ·   Checked by specProse.test.ts on every build.

/**
 * What the spec SAYS about each template, as opposed to what it lists.
 *
 * ⚠️ THIS GOES IN THE USER TURN, NOT IN `AD_PACK`, AND THAT IS A CACHING
 * DECISION RATHER THAN A TIDINESS ONE. The pack is the shared cached prefix
 * across all three call kinds and its measured floor is ~1,500 tokens against a
 * 1,024 minimum — under 50% headroom. Moving the four template descriptions out
 * to make room for four rationales risks dropping it under the threshold, where
 * the cache is SILENTLY IGNORED. ~400 uncached tokens on the copy call is a
 * fraction of a penny; a silently dead cache on every call is not.
 */
export const AD_SPEC_PROSE: Record<string, string> = {
  "never-see-the-messages": `Sells the absence of work rather than the presence of income, which is why it needs no figures and no photo. It is the template a customer with nothing but a logo can publish on day one.

What this template must never do: None. Nothing here states an outcome. The only customer-specific numbers are their fee and their own service list, both of which they control.`,
  "rules-keep-changing": `For the cautious landlord, the one who would short-let but is not sure it is allowed. Strongest in licensing areas, where the rules are the reason they have not started.

What this template must never do: None on income, but this template carries a different risk: it states what a customer handles. Only items they tick may appear, and the copy must never imply legal advice or that compliance is guaranteed. Suggested fixed line in the footer: "Responsibility stays with the property owner; we manage the process."`,
  "what-would-it-earn": `The volume template, and the one to make the default. It offers a calculation rather than a claim, which is why it can talk about income without triggering the gate: the number belongs to the landlord's own property and is produced after they enquire.

What this template must never do: The ad must never show an example estimate, not even a plausible one, because a specific figure in the creative is a claim regardless of the disclaimer beneath it. The open row shows what will be filled in, not what it will say. Pairs best with an instant lead form: postcode, bedrooms, current rent.`,
  "years-properties-review": `The trust template. A landlord hands over a property worth six figures, so the bar is higher than for most services. This one makes no argument at all: it states what the operator is and lets that do the work.

What this template must never do: Every figure is the customer's own and each must be entered, not inferred. The review score always renders with its count. A quote may only be used if the customer confirms it is real and published somewhere; store where it came from, exactly as with template 1's figures.`,
};
